Search.appendIndex(
    [
                {
            "fqsen": "\\Wojciech\\Phlambda\\adjust\u0028\u0029",
            "name": "adjust",
            "summary": "Return\u0020copy\u0020of\u0020an\u0020array\u0020with\u0020replaced\u0020element\u0020at\u0020given\u0020index.",
            "url": "namespaces/wojciech-phlambda.html#function_adjust"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\all\u0028\u0029",
            "name": "all",
            "summary": "Returns\u0020true\u0020if\u0020all\u0020elements\u0020from\u0020the\u0020array\u0020match\u0020the\u0020predicate,\u0020false\u0020if\nthere\u0020is\u0020any\u0020which\u0020doesn\u0027t.",
            "url": "namespaces/wojciech-phlambda.html#function_all"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\any\u0028\u0029",
            "name": "any",
            "summary": "Return\u0020true\u0020if\u0020any\u0020element\u0020matches\u0020given\u0020predicate.",
            "url": "namespaces/wojciech-phlambda.html#function_any"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\append\u0028\u0029",
            "name": "append",
            "summary": "Return\u0020copy\u0020of\u0020an\u0020array\u0020with\u0020given\u0020element\u0020appended\u0020at\u0020the\u0020end.",
            "url": "namespaces/wojciech-phlambda.html#function_append"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\concat\u0028\u0029",
            "name": "concat",
            "summary": "Concat\u0020two\u0020elements\u0020arrays\u0020or\u0020strings.",
            "url": "namespaces/wojciech-phlambda.html#function_concat"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\collectBy\u0028\u0029",
            "name": "collectBy",
            "summary": "Splits\u0020a\u0020list\u0020into\u0020sub\u002Dlist\u0020based\u0020on\u0020the\u0020result\u0020of\u0020calling\u0020a\u0020key\u002Dreturning\u0020function.",
            "url": "namespaces/wojciech-phlambda.html#function_collectBy"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\diff\u0028\u0029",
            "name": "diff",
            "summary": "Returns\u0020elements\u0020from\u0020first\u0020array,\u0020that\u0020are\u0020not\u0020present\u0020in\u0020second",
            "url": "namespaces/wojciech-phlambda.html#function_diff"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\drop\u0028\u0029",
            "name": "drop",
            "summary": "Return\u0020copy\u0020of\u0020an\u0020array\/string\u0020but\u0020without\u0020first\u0020\u0060n\u0060\u0020elements\u0020of\u0020the\u0020given\u0020\u0060input\u0060.",
            "url": "namespaces/wojciech-phlambda.html#function_drop"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\dropLast\u0028\u0029",
            "name": "dropLast",
            "summary": "Return\u0020copy\u0020of\u0020an\u0020array\u0020or\u0020string\u0020but\u0020without\u0020\u0060n\u0060\u0020last\u0020elements\u0020of\u0020the\u0020given\u0020\u0060input\u0060.",
            "url": "namespaces/wojciech-phlambda.html#function_dropLast"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\dropLastWhile\u0028\u0029",
            "name": "dropLastWhile",
            "summary": "Return\u0020copy\u0020of\u0020an\u0020array\u0020or\u0020string\u0020but\u0020without\u0020tailing\u0020elements\u0020which\u0020match\u0020predicate.",
            "url": "namespaces/wojciech-phlambda.html#function_dropLastWhile"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\dropRepeats\u0028\u0029",
            "name": "dropRepeats",
            "summary": "Return\u0020copy\u0020of\u0020an\u0020array\u0020but\u0020without\u0020repeating\u0020elements.",
            "url": "namespaces/wojciech-phlambda.html#function_dropRepeats"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\filter\u0028\u0029",
            "name": "filter",
            "summary": "Iterates\u0020over\u0020each\u0020element\u0020of\u0020given\u0020array\u0020and\u0020returns\u0020only\u0020those\u0020who\u0020matches\u0020given\u0020predicate.",
            "url": "namespaces/wojciech-phlambda.html#function_filter"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\flatMap\u0028\u0029",
            "name": "flatMap",
            "summary": "Works\u0020like\u0020map\u0020but\u0020result\u0020is\u0020single\u0020dimension\u0020array.",
            "url": "namespaces/wojciech-phlambda.html#function_flatMap"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\flat\u0028\u0029",
            "name": "flat",
            "summary": "Makes\u0020single\u0020dimension\u0020array\u0020from\u0020mulit\u002Ddimension\u0020one.",
            "url": "namespaces/wojciech-phlambda.html#function_flat"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\map\u0028\u0029",
            "name": "map",
            "summary": "Applies\u0020given\u0020function\u0020to\u0020each\u0020element\u0020of\u0020the\u0020array\u0020and\u0020return\u0020new\u0020one\u0020with\u0020the\u0020results.",
            "url": "namespaces/wojciech-phlambda.html#function_map"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\reduce\u0028\u0029",
            "name": "reduce",
            "summary": "Reduces\u0020array\u0020to\u0020single\u0020value\u0020using\u0020provided\u0020callback.",
            "url": "namespaces/wojciech-phlambda.html#function_reduce"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\tuples\u0028\u0029",
            "name": "tuples",
            "summary": "Returns\u0020new\u0020list,\u0020composed\u0020of\u0020n\u002Dtuples\u0020of\u0020consecutive\u0020elements.",
            "url": "namespaces/wojciech-phlambda.html#function_tuples"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\_\u0028\u0029",
            "name": "_",
            "summary": "Wraps\u0020array\u0020with\u0020Wrapper\u0020object.",
            "url": "namespaces/wojciech-phlambda.html#function__"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\adjust",
            "name": "adjust",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_adjust"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\all",
            "name": "all",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_all"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\any",
            "name": "any",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_any"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\append",
            "name": "append",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_append"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\concat",
            "name": "concat",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_concat"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\collectBy",
            "name": "collectBy",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_collectBy"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\diff",
            "name": "diff",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_diff"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\drop",
            "name": "drop",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_drop"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\dropLast",
            "name": "dropLast",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_dropLast"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\dropLastWhile",
            "name": "dropLastWhile",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_dropLastWhile"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\dropRepeats",
            "name": "dropRepeats",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_dropRepeats"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\filter",
            "name": "filter",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_filter"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\flatMap",
            "name": "flatMap",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_flatMap"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\flat",
            "name": "flat",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_flat"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\map",
            "name": "map",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_map"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\reduce",
            "name": "reduce",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_reduce"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\tuples",
            "name": "tuples",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_tuples"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\_",
            "name": "_",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant__"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\curryN",
            "name": "curryN",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_curryN"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\curry3",
            "name": "curry3",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_curry3"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\curry2",
            "name": "curry2",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_curry2"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\curry",
            "name": "curry",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_curry"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\__",
            "name": "__",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant___"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\_and",
            "name": "_and",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant__and"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\both",
            "name": "both",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_both"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\either",
            "name": "either",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_either"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\not",
            "name": "not",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_not"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\neither",
            "name": "neither",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_neither"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\_or",
            "name": "_or",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant__or"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\add",
            "name": "add",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_add"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\subtract",
            "name": "subtract",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_subtract"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\dec",
            "name": "dec",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_dec"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\inc",
            "name": "inc",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_inc"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\divide",
            "name": "divide",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_divide"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\multiply",
            "name": "multiply",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_multiply"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\sum",
            "name": "sum",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_sum"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\below",
            "name": "below",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_below"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\above",
            "name": "above",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_above"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\ofType",
            "name": "ofType",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_ofType"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\toString",
            "name": "toString",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_toString"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\startsWith",
            "name": "startsWith",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_startsWith"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\endsWith",
            "name": "endsWith",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_endsWith"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\matches",
            "name": "matches",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_matches"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\clamp",
            "name": "clamp",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html#constant_clamp"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\curryN\u0028\u0029",
            "name": "curryN",
            "summary": "Returns\u0020n\u0020currying\u0020function.",
            "url": "namespaces/wojciech-phlambda.html#function_curryN"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\curry3\u0028\u0029",
            "name": "curry3",
            "summary": "Returns\u0020currying\u0020function\u0020awaiting\u00203\u0020arguments.",
            "url": "namespaces/wojciech-phlambda.html#function_curry3"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\curry2\u0028\u0029",
            "name": "curry2",
            "summary": "Returns\u0020currying\u0020function\u0020awaiting\u00202\u0020arguments.",
            "url": "namespaces/wojciech-phlambda.html#function_curry2"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\curry\u0028\u0029",
            "name": "curry",
            "summary": "Returns\u0020currying\u0020function\u0020awaiting\u00201\u0020argument.",
            "url": "namespaces/wojciech-phlambda.html#function_curry"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\__\u0028\u0029",
            "name": "__",
            "summary": "Returns\u0020placeholder\u0020for\u0020omitting\u0020some\u0020arguments\u0020in\u0020currying\u0020functions.",
            "url": "namespaces/wojciech-phlambda.html#function___"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Internal\\Attributes\\ShouldNotBeImplementedInWrapper",
            "name": "ShouldNotBeImplementedInWrapper",
            "summary": "Attribute\u0020to\u0020mark\u0020methods\u0020that\u0020are\u0020not\u0020supposed\u0020to\u0020be\u0020implemented\u0020by\u0020Wrapper.",
            "url": "classes/Wojciech-Phlambda-Internal-Attributes-ShouldNotBeImplementedInWrapper.html"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Internal\\Classes\\CurryingFunction",
            "name": "CurryingFunction",
            "summary": "Internal\u0020class\u0020that\u0020encapsulates\u0020currying\u0020functions\u0020generation\u0020and\u0020logic.",
            "url": "classes/Wojciech-Phlambda-Internal-Classes-CurryingFunction.html"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Internal\\Classes\\CurryingFunction\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Wojciech-Phlambda-Internal-Classes-CurryingFunction.html#method___construct"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Internal\\Classes\\CurryingFunction\u003A\u003A__invoke\u0028\u0029",
            "name": "__invoke",
            "summary": "Depend\u0020on\u0020number\u0020of\u0020expected\u0020arguments\u0020given\u0020in\u0020constructor\u0020and\u0020number\u0020of\u0020arguments\ngiven\u0020to\u0020this\u0020method,\u00203\u0020things\u0020can\u0020happen\u003A\n\u0020\u002D\u0020when\u0020number\u0020of\u0020arguments\u0020equals\u0020expected\u0020number,\u0020given\u0020callable\u0020will\u0020be\u0020called\u0020with\u0020all\u0020arguments\u0020and\u0020result\nwill\u0020be\u0020returned.",
            "url": "classes/Wojciech-Phlambda-Internal-Classes-CurryingFunction.html#method___invoke"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Internal\\Classes\\CurryingFunction\u003A\u003AisMoreThenExpectedArgumentsGiven\u0028\u0029",
            "name": "isMoreThenExpectedArgumentsGiven",
            "summary": "",
            "url": "classes/Wojciech-Phlambda-Internal-Classes-CurryingFunction.html#method_isMoreThenExpectedArgumentsGiven"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Internal\\Classes\\CurryingFunction\u003A\u003A\u0024numberOfExpectedArguments",
            "name": "numberOfExpectedArguments",
            "summary": "",
            "url": "classes/Wojciech-Phlambda-Internal-Classes-CurryingFunction.html#property_numberOfExpectedArguments"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Internal\\Classes\\CurryingFunction\u003A\u003AareAllPassed\u0028\u0029",
            "name": "areAllPassed",
            "summary": "",
            "url": "classes/Wojciech-Phlambda-Internal-Classes-CurryingFunction.html#method_areAllPassed"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Internal\\Classes\\CurryingFunction\u003A\u003AnoArgumentsAreGiven\u0028\u0029",
            "name": "noArgumentsAreGiven",
            "summary": "",
            "url": "classes/Wojciech-Phlambda-Internal-Classes-CurryingFunction.html#method_noArgumentsAreGiven"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Internal\\Classes\\CurryingFunction\u003A\u003AupdatePassedArguments\u0028\u0029",
            "name": "updatePassedArguments",
            "summary": "",
            "url": "classes/Wojciech-Phlambda-Internal-Classes-CurryingFunction.html#method_updatePassedArguments"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Internal\\Classes\\CurryingFunction\u003A\u003AreplacePlaceholderWithArgument\u0028\u0029",
            "name": "replacePlaceholderWithArgument",
            "summary": "",
            "url": "classes/Wojciech-Phlambda-Internal-Classes-CurryingFunction.html#method_replacePlaceholderWithArgument"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Internal\\Classes\\CurryingFunction\u003A\u003A\u0024callable",
            "name": "callable",
            "summary": "",
            "url": "classes/Wojciech-Phlambda-Internal-Classes-CurryingFunction.html#property_callable"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Internal\\Classes\\CurryingFunction\u003A\u003A\u0024passedArguments",
            "name": "passedArguments",
            "summary": "",
            "url": "classes/Wojciech-Phlambda-Internal-Classes-CurryingFunction.html#property_passedArguments"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Internal\\Classes\\Placeholder",
            "name": "Placeholder",
            "summary": "Object\u0020used\u0020in\u0020currying\u0020functions\u0020to\u0020omit\u0020some\u0020parameter.",
            "url": "classes/Wojciech-Phlambda-Internal-Classes-Placeholder.html"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Internal\\Classes\\Placeholder\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/Wojciech-Phlambda-Internal-Classes-Placeholder.html#method_create"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Internal\\Classes\\Placeholder\u003A\u003AisPlaceholder\u0028\u0029",
            "name": "isPlaceholder",
            "summary": "",
            "url": "classes/Wojciech-Phlambda-Internal-Classes-Placeholder.html#method_isPlaceholder"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Internal\\Classes\\Placeholder\u003A\u003AfilterPlaceholders\u0028\u0029",
            "name": "filterPlaceholders",
            "summary": "Returns\u0020new\u0020array\u0020without\u0020placeholders.",
            "url": "classes/Wojciech-Phlambda-Internal-Classes-Placeholder.html#method_filterPlaceholders"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Internal\\Exceptions\\TooMuchArgumentsGiven",
            "name": "TooMuchArgumentsGiven",
            "summary": "",
            "url": "classes/Wojciech-Phlambda-Internal-Exceptions-TooMuchArgumentsGiven.html"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Internal\\Exceptions\\TooMuchArgumentsGiven\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/Wojciech-Phlambda-Internal-Exceptions-TooMuchArgumentsGiven.html#method_create"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\_and\u0028\u0029",
            "name": "_and",
            "summary": "Function\u0020returns\u0020\u0060true\u0060\u0020if\u0020both\u0020arguments\u0020are\u0020\u0060true\u0060\u003B",
            "url": "namespaces/wojciech-phlambda.html#function__and"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\both\u0028\u0029",
            "name": "both",
            "summary": "Function\u0020calling\u0020two\u0020provided\u0020functions\u0020and\u0020returning\u0020the\u0020\u0060\u0026\u0026\u0060\u0020of\u0020the\u0020results.",
            "url": "namespaces/wojciech-phlambda.html#function_both"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\either\u0028\u0029",
            "name": "either",
            "summary": "Function\u0020calling\u0020two\u0020provided\u0020functions\u0020and\u0020returning\u0020the\u0020\u0060\u007C\u007C\u0060\u0020of\u0020the\u0020results.",
            "url": "namespaces/wojciech-phlambda.html#function_either"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\not\u0028\u0029",
            "name": "not",
            "summary": "Function\u0020returns\u0020inverted\u0020result\u0020of\u0020the\u0020input.",
            "url": "namespaces/wojciech-phlambda.html#function_not"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\neither\u0028\u0029",
            "name": "neither",
            "summary": "Function\u0020calling\u0020two\u0020provided\u0020functions\u0020and\u0020returning\u0020true\u0020when\u0020both\u0020are\u0020returning\u0020false.",
            "url": "namespaces/wojciech-phlambda.html#function_neither"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\_or\u0028\u0029",
            "name": "_or",
            "summary": "Function\u0020returns\u0020\u0060true\u0060\u0020if\u0020at\u0020least\u0020one\u0020arguments\u0020is\u0020\u0060true\u0060\u003B",
            "url": "namespaces/wojciech-phlambda.html#function__or"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\add\u0028\u0029",
            "name": "add",
            "summary": "Returns\u0020sum\u0020of\u0020two\u0020numbers.",
            "url": "namespaces/wojciech-phlambda.html#function_add"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\subtract\u0028\u0029",
            "name": "subtract",
            "summary": "Returns\u0020subtraction\u0020of\u0020two\u0020numbers.",
            "url": "namespaces/wojciech-phlambda.html#function_subtract"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\dec\u0028\u0029",
            "name": "dec",
            "summary": "Decreases\u0020number\u0020by\u00201.",
            "url": "namespaces/wojciech-phlambda.html#function_dec"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\inc\u0028\u0029",
            "name": "inc",
            "summary": "Increases\u0020number\u0020by\u00201.",
            "url": "namespaces/wojciech-phlambda.html#function_inc"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\divide\u0028\u0029",
            "name": "divide",
            "summary": "Divides\u0020two\u0020numbers.",
            "url": "namespaces/wojciech-phlambda.html#function_divide"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\multiply\u0028\u0029",
            "name": "multiply",
            "summary": "Multiplies\u0020two\u0020numbers.",
            "url": "namespaces/wojciech-phlambda.html#function_multiply"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\sum\u0028\u0029",
            "name": "sum",
            "summary": "Returns\u0020sum\u0020of\u0020all\u0020elements.",
            "url": "namespaces/wojciech-phlambda.html#function_sum"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\below\u0028\u0029",
            "name": "below",
            "summary": "Returns\u0020function\u0020checking\u0020if\u0020given\u0020value\u0020is\u0020below\u0020expected.",
            "url": "namespaces/wojciech-phlambda.html#function_below"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\above\u0028\u0029",
            "name": "above",
            "summary": "Returns\u0020function\u0020checking\u0020if\u0020given\u0020value\u0020is\u0020above\u0020expected.",
            "url": "namespaces/wojciech-phlambda.html#function_above"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\ofType\u0028\u0029",
            "name": "ofType",
            "summary": "Returns\u0020function\u0020that\u0020check\u0020if\u0020value\u0020is\u0020instance\u0020of\u0020given\u0020type.",
            "url": "namespaces/wojciech-phlambda.html#function_ofType"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\clamp\u0028\u0029",
            "name": "clamp",
            "summary": "Restricts\u0020value\u0020to\u0020given\u0020minimum\u0020and\u0020maximum.",
            "url": "namespaces/wojciech-phlambda.html#function_clamp"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\toString\u0028\u0029",
            "name": "toString",
            "summary": "Converts\u0020value\u0020to\u0020string.",
            "url": "namespaces/wojciech-phlambda.html#function_toString"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\startsWith\u0028\u0029",
            "name": "startsWith",
            "summary": "Returns\u0020true\u0020if\u0020given\u0020\u0060\u0024item\u0060\u0020starts\u0020with\u0020\u0060\u0024expected\u0060\u0020value.",
            "url": "namespaces/wojciech-phlambda.html#function_startsWith"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\endsWith\u0028\u0029",
            "name": "endsWith",
            "summary": "Returns\u0020true\u0020if\u0020given\u0020\u0060\u0024item\u0060\u0020ends\u0020with\u0020\u0060\u0024expected\u0060\u0020value.",
            "url": "namespaces/wojciech-phlambda.html#function_endsWith"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\matches\u0028\u0029",
            "name": "matches",
            "summary": "Test\u0020regular\u0020expression\u0020against\u0020a\u0020sting.\u0020Returns\u0020all\u0020matching\u0020elements\u0020or\u0020empty\u0020array\u0020if\u0020there\u0020aren\u0027t\u0020any.",
            "url": "namespaces/wojciech-phlambda.html#function_matches"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Wrapper",
            "name": "Wrapper",
            "summary": "This\u0020class\u0020is\u0020a\u0020wrapper\u0020for\u0020arrays,\u0020so\u0020you\u0020can\u0020chain\u0020functions\u0020from\u0020that\u0020library\u0020in\u0020nice\u0020fashion.",
            "url": "classes/Wojciech-Phlambda-Wrapper.html"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Wrapper\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Wojciech-Phlambda-Wrapper.html#method___construct"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Wrapper\u003A\u003Awrap\u0028\u0029",
            "name": "wrap",
            "summary": "",
            "url": "classes/Wojciech-Phlambda-Wrapper.html#method_wrap"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Wrapper\u003A\u003AgetIterator\u0028\u0029",
            "name": "getIterator",
            "summary": "",
            "url": "classes/Wojciech-Phlambda-Wrapper.html#method_getIterator"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Wrapper\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Wojciech-Phlambda-Wrapper.html#method_count"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Wrapper\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/Wojciech-Phlambda-Wrapper.html#method_offsetExists"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Wrapper\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/Wojciech-Phlambda-Wrapper.html#method_offsetGet"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Wrapper\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "",
            "url": "classes/Wojciech-Phlambda-Wrapper.html#method_offsetSet"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Wrapper\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/Wojciech-Phlambda-Wrapper.html#method_offsetUnset"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Wrapper\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Wojciech-Phlambda-Wrapper.html#method_toArray"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Wrapper\u003A\u003Aadjust\u0028\u0029",
            "name": "adjust",
            "summary": "Return\u0020copy\u0020of\u0020an\u0020array\u0020with\u0020replaced\u0020element\u0020at\u0020given\u0020index.",
            "url": "classes/Wojciech-Phlambda-Wrapper.html#method_adjust"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Wrapper\u003A\u003Aall\u0028\u0029",
            "name": "all",
            "summary": "Returns\u0020true\u0020if\u0020all\u0020elements\u0020from\u0020the\u0020array\u0020match\u0020the\u0020predicate,\u0020false\u0020if\nthere\u0020is\u0020any\u0020which\u0020doesn\u0027t.",
            "url": "classes/Wojciech-Phlambda-Wrapper.html#method_all"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Wrapper\u003A\u003Aany\u0028\u0029",
            "name": "any",
            "summary": "Return\u0020true\u0020if\u0020any\u0020element\u0020matches\u0020given\u0020predicate.",
            "url": "classes/Wojciech-Phlambda-Wrapper.html#method_any"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Wrapper\u003A\u003Aappend\u0028\u0029",
            "name": "append",
            "summary": "Return\u0020copy\u0020of\u0020an\u0020array\u0020with\u0020given\u0020element\u0020appended\u0020at\u0020the\u0020end.",
            "url": "classes/Wojciech-Phlambda-Wrapper.html#method_append"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Wrapper\u003A\u003Aconcat\u0028\u0029",
            "name": "concat",
            "summary": "Concat\u0020this\u0020array\u0020with\u0020given\u0020one\u0020\u0028Wrapper\u0020may\u0020be\u0020passed\u0020too\u0029.",
            "url": "classes/Wojciech-Phlambda-Wrapper.html#method_concat"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Wrapper\u003A\u003Adiff\u0028\u0029",
            "name": "diff",
            "summary": "Returns\u0020difference\u0020between\u0020this\u0020object\u0020and\u0020given\u0020array\u0020or\u0020wrapper.",
            "url": "classes/Wojciech-Phlambda-Wrapper.html#method_diff"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Wrapper\u003A\u003Adrop\u0028\u0029",
            "name": "drop",
            "summary": "Return\u0020copy\u0020but\u0020without\u0020first\u0020\u0060n\u0060\u0020elements\u0020of\u0020the\u0020given\u0020\u0060input\u0060.",
            "url": "classes/Wojciech-Phlambda-Wrapper.html#method_drop"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Wrapper\u003A\u003AdropLast\u0028\u0029",
            "name": "dropLast",
            "summary": "Return\u0020copy\u0020but\u0020without\u0020\u0060n\u0060\u0020last\u0020elements\u0020of\u0020the\u0020given\u0020\u0060input\u0060.",
            "url": "classes/Wojciech-Phlambda-Wrapper.html#method_dropLast"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Wrapper\u003A\u003Afilter\u0028\u0029",
            "name": "filter",
            "summary": "Returns\u0020list\u0020with\u0020only\u0020values\u0020matching\u0020given\u0020predicate.",
            "url": "classes/Wojciech-Phlambda-Wrapper.html#method_filter"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Wrapper\u003A\u003AdropRepeats\u0028\u0029",
            "name": "dropRepeats",
            "summary": "Return\u0020copy\u0020but\u0020without\u0020repeating\u0020elements.",
            "url": "classes/Wojciech-Phlambda-Wrapper.html#method_dropRepeats"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Wrapper\u003A\u003AflatMap\u0028\u0029",
            "name": "flatMap",
            "summary": "Applies\u0020given\u0020function\u0020to\u0020each\u0020element\u0020of\u0020the\u0020array\u0020and\u0020return\u0020new\u0020one\u0020with\u0020the\u0020results\u0020flatten\u0020to\u0020single\u0020dimension.",
            "url": "classes/Wojciech-Phlambda-Wrapper.html#method_flatMap"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Wrapper\u003A\u003Amap\u0028\u0029",
            "name": "map",
            "summary": "Applies\u0020given\u0020function\u0020to\u0020each\u0020element\u0020of\u0020the\u0020array\u0020and\u0020return\u0020new\u0020one\u0020with\u0020the\u0020results.",
            "url": "classes/Wojciech-Phlambda-Wrapper.html#method_map"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Wrapper\u003A\u003Areduce\u0028\u0029",
            "name": "reduce",
            "summary": "Reduces\u0020array\u0020to\u0020single\u0020value\u0020using\u0020provided\u0020callback.",
            "url": "classes/Wojciech-Phlambda-Wrapper.html#method_reduce"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Wrapper\u003A\u003A\u0024array",
            "name": "array",
            "summary": "",
            "url": "classes/Wojciech-Phlambda-Wrapper.html#property_array"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Wojciech\\Phlambda",
            "name": "Phlambda",
            "summary": "",
            "url": "namespaces/wojciech-phlambda.html"
        },                {
            "fqsen": "\\Wojciech",
            "name": "Wojciech",
            "summary": "",
            "url": "namespaces/wojciech.html"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Internal\\Attributes",
            "name": "Attributes",
            "summary": "",
            "url": "namespaces/wojciech-phlambda-internal-attributes.html"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Internal",
            "name": "Internal",
            "summary": "",
            "url": "namespaces/wojciech-phlambda-internal.html"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Internal\\Classes",
            "name": "Classes",
            "summary": "",
            "url": "namespaces/wojciech-phlambda-internal-classes.html"
        },                {
            "fqsen": "\\Wojciech\\Phlambda\\Internal\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/wojciech-phlambda-internal-exceptions.html"
        }            ]
);
