language: php
dist: bionic
php:
  - 8.0
  - 8.1

env:
  global:
    - XDEBUG_MODE=coverage

install:
  - composer self-update
  - composer install
  - composer require -w php-coveralls/php-coveralls:^2

before_script:
  - mkdir -p build/logs
  - cp phpunit.xml.dist phpunit.xml
  - cp infection.json.dist infection.json

script:
  - make test-full
after_success:
  - sh -c 'if( [ "$TRAVIS_PHP_VERSION" != "hhvm" ] ); then php vendor/bin/php-coveralls -v; fi;'