name: Makefile CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build
      run: make build-docs
    
    - name: Debug
      run: ls -la
      
    - name: Pack docs
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r docs.zip . -i docs
        
    - name: Make artifact
      uses: actions/upload-artifact@v2
      with:
        name: github-pages
        path: docs.zip
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: github-pages
    
    - uses: montudor/action-zip@v1
      with:
        args: unzip -qq docs.zip -d docs

    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    
