name: Makefile CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build
      run: make build-docs
      
    - name: Pack docs
      run: sudo tar -czvf docs.tar.gz docs
        
    - name: Make artifact
      uses: actions/upload-artifact@v2
      with:
        name: github-pages
        path: docs.tar.gz
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: github-pages
    
    - run: tar -xzvf docs.tar.gz -C ./public
    
    - run: ls -la

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
    
    
